config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home' => 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, execept: [:destroy]

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'

  resource :messages, only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :chef_id, presence: true
  
  belongs_to :chef
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :image, ImageUploader
  
  default_scope -> { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully"
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    @comment = Comment.new
  end

  def edit
    
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end

  def like
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end

  private

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(
        :name,
        :description,
        :image,
        ingredient_ids: []
      )
    end

    def require_same_user
      if current_chef != @recipe.chef && !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end

    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_to :back
      end
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row>">
  <div class="col-md-12">
    <%= form_for(@recipe, html: { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |ingredient| %>
              <% ingredient.label(class: "checkbox-inline input_checkbox") {ingredient.check_box(class: "checkbox") + ingredient.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :image, "Add Image" %>
        </div>
        <div class="col-md-8">
          <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef-info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
        | <%= pluralize(recipe.comments.count, "Comment") %></small></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?)%>
        <div class="recipe-actions">
          <%= link_to 'Edit this recipe', edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe" }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
      <div class="row">
        <div class="pull-right liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>
          <% end %> <%= recipe.thumbs_up_total %> ||
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
          <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <%= image_tag(recipe.image.url, size: "150x100") if recipe.image? %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="well col-md-8 col-md-offset-2">
  <div align="center">
    <%= image_tag @recipe.image.url if @recipe.image? %>
  </div>
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr>
  <%= simple_format(@recipe.description) %>
  <hr>
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right">created: <%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef.chefname == @recipe.chef.chefname || current_chef.admin?) %>
      <%= link_to 'Edit this recipe', edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe" }, class: "btn btn-xs btn-danger"  %>
    <% end %>
    <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
  </div>
  <div class="row liking">
    <div class="row col-md-8 col-md-offset-2">
      <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i>
      <% end %> <%= @recipe.thumbs_up_total %> ||
      <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i>
      <% end %> <%= @recipe.thumbs_down_total %>
    </div>
  </div>
</div>

<% if logged_in? %>

  <div class="row>">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr>
      <%= form_for([@recipe, @comment], remote: true, html: { class: "form-horizontal", role: "form" }) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter comment" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr>
    </div>
  </div>
<% end %>

<% if @recipe.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: "comments/comments", object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>