config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home' => 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, execept: [:destroy]

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'

  resource :messages, only: [:create]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates_uniqueness_of :name

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_admin, only: [:new, :create, :edit, :update]

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5).order('name')
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully created"
      redirect_to ingredient_path(@ingredient)
    else
      render :new
    end
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit

  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient name was updated successfully"
      redirect_to ingredient_path(@ingredient)
    else
      render :edit
    end
  end

  private

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(
        :name
      )
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_chef.admin?)
        flash[:danger] = "Only admin users can perform that action"
        redirect_to ingredients_path
      end
    end
end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>

<div class="row>">
  <div class="col-md-12">
    <%= form_for(@ingredient, html: { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/edit.html.erb
<%= render "shared/page_title", title: "edit an ingredient" %>
<%= render "form" %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Showing available ingredients" %>

<div align="center">
  <%= will_paginate %>
  <% @ingredients.each do |ing| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="chef-title"><%= link_to ing.name.capitalize, ingredient_path(ing) %></li>
          <li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>
          <% if logged_in? && current_chef.admin? %>

            <li><%= link_to "Edit this ingredient", edit_ingredient_path(ing) %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render "shared/page_title", title: "enter a new ingredient" %>
<%= render "form" %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name}" %>

<% if @ingredient.recipes.count != 0 %>
  <h4 align="center">Recipe's containing <%= @ingredient.name %></h4>
  <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
  <%= render 'recipes/recipe', obj: @ingredient_recipes %>
  <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
<% else %>
  <h4 align="center">No recipes yet</h4>
<% end %>