config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home' => 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, execept: [:destroy]

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'

  resource :messages, only: [:create]
end

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to MyRecipes App</h1>
  <h2>The Best Recipe Sharing App</h2>
  <p><%= link_to "Sign Up Today", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<!-- Example row of columns -->
<div class="row">
  <div class="col-lg-4">
    <h2>Great Recipes</h2>
    <p>Create recipes, eat healthy, eat unhealthy, eat delicious. </p>
    <p><%= link_to "View Details", recipes_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
  <div class="col-lg-4">
    <h2>Meet New Chefs</h2>
    <p>Recipes can be viewed by everyone, share your food. </p>
    <p><%= link_to "View Details", chefs_path, class: "btn btn-primary btn-xlarge" %></p>
 </div>
  <div class="col-lg-4">
    <h2>Many Ingredients</h2>
    <p>Cook, eat, share, sleep, and repeat.</p>
    <p><%= link_to "View Details", ingredients_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
</div>