config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home' => 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, execept: [:destroy]

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'

  resource :messages, only: [:create]
end

app/views/layouts/_footer.html.erb
<!-- <footer class="footer center">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer> -->

<!-- <div class="footer footer-fix">
  <p>&copy; MyRecipes 2015</p>
</div> -->

<footer class="footer">
  <nav>
    <ul>
      <li>&copy; MyRecipes 2015</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ChefChat", chat_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create a new recipe", new_recipe_path %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_chef.admin? %>
              <li><%= link_to "New Ingredient", new_ingredient_path %></li>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to "All Ingredients", ingredients_path %></li>
            <%# Ingredient.all.each do |ingredient| %>
              <li><%#= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
            <%# end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit Profile", edit_chef_path(current_chef) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%=link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycookbook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <div class="container">
      <div class="main-footer">
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>